Add cache support
GuillaumeAmat/leaflet-overpass-layer pull request #41
Opened 2021-09-25 17:22 UTC by fodor0205

2021-10-16 14:28 UTC, GuillaumeAmat requested changes
Thanks for that great improvement @fodor0205 (and sorry for the delay...)

2021-10-16 14:28 UTC, GuillaumeAmat commented on src/OverPassLayer.js
> +    }
I would rather extract that logic into another function and call it at the end of `onAdd`. WDYT?

2021-11-13 16:18 UTC, fodor0205 commented on src/OverPassLayer.js
> +    }
`getAll()` and `getAllKeys()` need to be ran after the `idb` connection is initialized which was done with the first `await` in the original method.

By extracting this method, the new cache loading method needs to run after this db creation.

[I've come up with a solution here](https://github.com/fodor0205/leaflet-overpass-layer/compare/cache...fodor0205:cache-extract-method#diff-0d6519c7bcdb5bbe065a018683c82417df98945d974bcdcc4c94250b60439c37R413)

`onAdd()` cannot use await (it cannot be converted to be `async`, it comes from Leaflet), so I ended up periodically checking with `setTimeout()` until `idb` is available.

If you think this is good enough, I can push these changes to this Pull Request too, but if have other or better idea, let me know.

2022-01-13 23:21 UTC, fodor0205 commented on src/OverPassLayer.js
> +    }
I've improved the code based on your feedback, while adding 2 new features:
- query is stored for cache items, so different queries have different cache items
- existing items are checked before storing new cache item to prevent duplications

2022-02-01 21:01 UTC, GuillaumeAmat approved these changes

2022-02-01 21:01 UTC, GuillaumeAmat commented
That's a great addition to the plugin @fodor0205, thank you again for your PR, it's really appreciated :ok_hand:

2022-02-01 21:02 UTC, merged